// Theme definitions with names
const themes = {
    "Midnight": {
        bgPrimary:       "#1a1b26",  
        bgSecondary:     "#101022", 
        bgCard:          "#282637",     
        bgCardCopied:    "#272b43",
        bgModal:         "#242837",     
        bgBreadCrumb:    "#0e0e17",
        accent:          "#0058b1",     
        accentLight:     "#5bedf7", 
        textPrimary:     "#e2e8ff",     
        textSecondary:   "#d1d7f1",   
        textHalfOpacity: "#c1ccff80",
        danger:          "#c8324e",  
        success:         "#6ca62e",  
        warning:         "#db942a" 
    },
    "Deep Space": {
        bgPrimary:       "#0e033a",
        bgSecondary:     "#040449",
        bgCard:          "#041162",
        bgCardCopied:    "#041D6A",
        bgModal:         "#05115d",
        bgBreadCrumb:    "#020029",
        accent:          "#0003ba",
        accentLight:     "#47bfff",
        textPrimary:     "#e7f4ff",
        textSecondary:   "#cfe4ff",
        textHalfOpacity: "#dbeeff80",
        danger:          "#e12b2b",
        success:         "#22c55e",
        warning:         "#f59e0b"
    },
    "Ocean": {
        bgPrimary:       "#00252e",
        bgSecondary:     "#03181d",
        bgCard:          "#083847",
        bgCardCopied:    "#0d4a5a",
        bgModal:         "#0a3a3f",
        bgBreadCrumb:    "#0e1d22",
        accent:          "#008751",     
        accentLight:     "#00fff7", 
        textPrimary:     "#effff8", 
        textSecondary:   "#daf2f2",
        textHalfOpacity: "#c1fff980",
        danger:          "#d42623", 
        success:         "#00aa06", 
        warning:         "#b58900" 
    },
    "Aurora": {
        bgPrimary:       "#051933",
        bgSecondary:     "#040d26", 
        bgCard:          "#0e284a",     
        bgCardCopied:    "#122e54",
        bgModal:         "#0a2643",
        bgBreadCrumb:    "#470c20",
        accent:          "#b00c2a",
        accentLight:     "#45fff3", 
        textPrimary:     "#ecfffd", 
        textSecondary:   "#d1faff",
        textHalfOpacity: "#cae5ff80",
        danger:          "#9d0000", 
        success:         "#009442", 
        warning:         "#ffd166"
    },
    "Wood": {
        bgPrimary:       "#9a6e52",   
        bgSecondary:     "#58241a",   
        bgCard:          "#663722",
        bgCardCopied:    "#945639",
        bgModal:         "#2a0f1f",
        bgBreadCrumb:    "#41140d",
        accent:          "#872020",   
        accentLight:     "#ffd5b3",   
        textPrimary:     "#ffffff",
        textSecondary:   "#ffefff",
        textHalfOpacity: "#ffffff8e",
        danger:          "#dc294a",
        success:         "#75ba1a",
        warning:         "#ffb703"
    },
    "Charcoal": {
        bgPrimary:       "#171717", 
        bgSecondary:     "#252525",
        bgCard:          "#353535",
        bgCardCopied:    "#2e659f",
        bgModal:         "#1e1e1e",
        bgBreadCrumb:    "#0f0f0f",
        accent:          "#b90000",
        accentLight:     "#ffffff",
        textPrimary:     "#ededed",
        textSecondary:   "#dfdfdf",
        textHalfOpacity: "#e0e0e080",
        danger:          "#761527",
        success:         "#2a825b",
        warning:         "#ffd54f"
    },
    "Slate": {
        bgPrimary:       "#2a2a2a",   
        bgSecondary:     "#1b1b1b",   
        bgCard:          "#454545",   
        bgCardCopied:    "#5c5c5c",   
        bgModal:         "#272727",
        bgBreadCrumb:    "#141414",
        accent:          "#0034c3",   
        accentLight:     "#55f1ff",   
        textPrimary:     "#f6f6f6",   
        textSecondary:   "#e2e2e2",   
        textHalfOpacity: "#d3d3d3be",
        danger:          "#a52121",   
        success:         "#279d27",   
        warning:         "#a68a6a"    
    },
    "Light": {
        bgPrimary:       "#dfebef",   
        bgSecondary:     "#cedae1",   
        bgCard:          "#c2e4d9",
        bgCardCopied:    "#b9d7c6",
        bgModal:         "#bbc6d8",
        bgBreadCrumb:    "#b1bfe1",
        accent:          "#b91a64",   
        accentLight:     "#ec4f8e",   
        textPrimary:     "#000000",
        textSecondary:   "#15141a",
        textHalfOpacity: "#000000be",
        danger:          "#ff4173",
        success:         "#42ff71",
        warning:         "#ffb703"
    },
    "Sakura": {
        bgPrimary:       "#fff8fb",
        bgSecondary:     "#fee4ee",
        bgCard:          "#ffffff",
        bgCardCopied:    "#f9dce7",
        bgModal:         "#fff4f8",
        bgBreadCrumb:    "#ffc9df",
        accent:          "#fc84a6",
        accentLight:     "#fb3d8c",
        textPrimary:     "#4a1f33",
        textSecondary:   "#68344b",
        textHalfOpacity: "#5d3c4ba7",
        danger:          "#dd3a65",
        success:         "#30bd85",
        warning:         "#ca8832"
    },
    "Sunset": {
        bgPrimary:       "#b2d7de",   
        bgSecondary:     "#ca3c3c",   
        bgCard:          "#e98150",
        bgCardCopied:    "#db703e",
        bgModal:         "#2a0f1f",
        bgBreadCrumb:    "#3a4e9e",
        accent:          "#5057bb",   
        accentLight:     "#ecfdff",   
        textPrimary:     "#000000",
        textSecondary:   "#15141a",
        textHalfOpacity: "#000000be",
        danger:          "#ff6790",
        success:         "#7cff7a",
        warning:         "#ffb703"
    }
};

export default themes;
